/********************************************************************************
** Form generated from reading UI file 'keyboard.ui'
**
** Created: Sat Apr 8 23:12:01 2017
**      by: Qt User Interface Compiler version 4.7.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_KEYBOARD_H
#define UI_KEYBOARD_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Keyboard
{
public:
    QWidget *centralWidget;
    QPushButton *hz_1;
    QPushButton *pushButton_r;
    QPushButton *pushButton_t;
    QPushButton *hz_7;
    QPushButton *pushButton_j;
    QPushButton *pushButton_l;
    QPushButton *pushButton_g;
    QPushButton *pushButton_q;
    QPushButton *pushButton_pre;
    QPushButton *pushButton_z;
    QPushButton *pushButton_Enter;
    QPushButton *pushButton_i;
    QPushButton *pushButton_k;
    QPushButton *hz_4;
    QPushButton *hz_2;
    QPushButton *pushButton_v;
    QPushButton *pushButton_en_ch;
    QPushButton *hz_3;
    QPushButton *pushButton_x;
    QPushButton *pushButton_y;
    QPushButton *pushButton_u;
    QPushButton *pushButton_c;
    QPushButton *hz_10;
    QPushButton *pushButton_sign_dou;
    QPushButton *pushButton_p;
    QPushButton *pushButton_d;
    QPushButton *pushButton_h;
    QPushButton *hz_6;
    QPushButton *pushButton_e;
    QPushButton *pushButton_o;
    QPushButton *pushButton_a;
    QPushButton *hz_9;
    QPushButton *pushButton_s;
    QPushButton *pushButton_del;
    QPushButton *pushButton_esc;
    QPushButton *pushButton_cap;
    QPushButton *pushButton_space;
    QPushButton *pushButton_next;
    QPushButton *pushButton_n;
    QPushButton *pushButton_sign_fen;
    QPushButton *pushButton_w;
    QPushButton *pushButton_f;
    QPushButton *pushButton_sign_wen;
    QLabel *label;
    QPushButton *hz_5;
    QPushButton *pushButton_sign_ju;
    QPushButton *pinyin;
    QPushButton *pushButton_m;
    QPushButton *pushButton_b;
    QPushButton *pushButton_sign_tan;
    QPushButton *hz_8;

    void setupUi(QMainWindow *Keyboard)
    {
        if (Keyboard->objectName().isEmpty())
            Keyboard->setObjectName(QString::fromUtf8("Keyboard"));
        Keyboard->resize(359, 148);
        centralWidget = new QWidget(Keyboard);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        hz_1 = new QPushButton(centralWidget);
        hz_1->setObjectName(QString::fromUtf8("hz_1"));
        hz_1->setGeometry(QRect(35, 40, 25, 25));
        hz_1->setMaximumSize(QSize(40, 60));
        hz_1->setFocusPolicy(Qt::NoFocus);
        hz_1->setFlat(false);
        pushButton_r = new QPushButton(centralWidget);
        pushButton_r->setObjectName(QString::fromUtf8("pushButton_r"));
        pushButton_r->setGeometry(QRect(125, 65, 25, 25));
        pushButton_r->setMaximumSize(QSize(40, 50));
        pushButton_r->setFocusPolicy(Qt::NoFocus);
        pushButton_r->setFlat(false);
        pushButton_t = new QPushButton(centralWidget);
        pushButton_t->setObjectName(QString::fromUtf8("pushButton_t"));
        pushButton_t->setEnabled(true);
        pushButton_t->setGeometry(QRect(150, 65, 25, 25));
        pushButton_t->setMaximumSize(QSize(40, 50));
        pushButton_t->setFocusPolicy(Qt::NoFocus);
        pushButton_t->setFlat(false);
        hz_7 = new QPushButton(centralWidget);
        hz_7->setObjectName(QString::fromUtf8("hz_7"));
        hz_7->setGeometry(QRect(185, 40, 25, 25));
        hz_7->setMaximumSize(QSize(40, 60));
        hz_7->setFocusPolicy(Qt::NoFocus);
        hz_7->setFlat(false);
        pushButton_j = new QPushButton(centralWidget);
        pushButton_j->setObjectName(QString::fromUtf8("pushButton_j"));
        pushButton_j->setGeometry(QRect(205, 90, 25, 25));
        pushButton_j->setMaximumSize(QSize(40, 50));
        pushButton_j->setFocusPolicy(Qt::NoFocus);
        pushButton_j->setFlat(false);
        pushButton_l = new QPushButton(centralWidget);
        pushButton_l->setObjectName(QString::fromUtf8("pushButton_l"));
        pushButton_l->setGeometry(QRect(255, 90, 25, 25));
        pushButton_l->setMaximumSize(QSize(40, 50));
        pushButton_l->setFocusPolicy(Qt::NoFocus);
        pushButton_l->setFlat(false);
        pushButton_g = new QPushButton(centralWidget);
        pushButton_g->setObjectName(QString::fromUtf8("pushButton_g"));
        pushButton_g->setGeometry(QRect(155, 90, 25, 25));
        pushButton_g->setMaximumSize(QSize(40, 50));
        pushButton_g->setFocusPolicy(Qt::NoFocus);
        pushButton_g->setFlat(false);
        pushButton_q = new QPushButton(centralWidget);
        pushButton_q->setObjectName(QString::fromUtf8("pushButton_q"));
        pushButton_q->setGeometry(QRect(50, 65, 25, 25));
        pushButton_q->setMaximumSize(QSize(40, 50));
        pushButton_q->setMouseTracking(false);
        pushButton_q->setFocusPolicy(Qt::NoFocus);
        pushButton_q->setFlat(false);
        pushButton_pre = new QPushButton(centralWidget);
        pushButton_pre->setObjectName(QString::fromUtf8("pushButton_pre"));
        pushButton_pre->setGeometry(QRect(10, 40, 25, 25));
        pushButton_pre->setMaximumSize(QSize(50, 40));
        pushButton_pre->setFocusPolicy(Qt::NoFocus);
        pushButton_pre->setFlat(false);
        pushButton_z = new QPushButton(centralWidget);
        pushButton_z->setObjectName(QString::fromUtf8("pushButton_z"));
        pushButton_z->setGeometry(QRect(60, 115, 25, 25));
        pushButton_z->setMaximumSize(QSize(40, 50));
        pushButton_z->setFocusPolicy(Qt::NoFocus);
        pushButton_z->setFlat(false);
        pushButton_Enter = new QPushButton(centralWidget);
        pushButton_Enter->setObjectName(QString::fromUtf8("pushButton_Enter"));
        pushButton_Enter->setGeometry(QRect(309, 65, 41, 51));
        pushButton_Enter->setFocusPolicy(Qt::NoFocus);
        pushButton_Enter->setFlat(false);
        pushButton_i = new QPushButton(centralWidget);
        pushButton_i->setObjectName(QString::fromUtf8("pushButton_i"));
        pushButton_i->setGeometry(QRect(225, 65, 25, 25));
        pushButton_i->setMaximumSize(QSize(40, 50));
        pushButton_i->setFocusPolicy(Qt::NoFocus);
        pushButton_i->setFlat(false);
        pushButton_k = new QPushButton(centralWidget);
        pushButton_k->setObjectName(QString::fromUtf8("pushButton_k"));
        pushButton_k->setGeometry(QRect(230, 90, 25, 25));
        pushButton_k->setMaximumSize(QSize(40, 50));
        pushButton_k->setFocusPolicy(Qt::NoFocus);
        pushButton_k->setFlat(false);
        hz_4 = new QPushButton(centralWidget);
        hz_4->setObjectName(QString::fromUtf8("hz_4"));
        hz_4->setGeometry(QRect(110, 40, 25, 25));
        hz_4->setMaximumSize(QSize(40, 60));
        hz_4->setFocusPolicy(Qt::NoFocus);
        hz_4->setLayoutDirection(Qt::LeftToRight);
        hz_4->setFlat(false);
        hz_2 = new QPushButton(centralWidget);
        hz_2->setObjectName(QString::fromUtf8("hz_2"));
        hz_2->setGeometry(QRect(60, 40, 25, 25));
        hz_2->setMaximumSize(QSize(40, 60));
        hz_2->setFocusPolicy(Qt::NoFocus);
        hz_2->setFlat(false);
        pushButton_v = new QPushButton(centralWidget);
        pushButton_v->setObjectName(QString::fromUtf8("pushButton_v"));
        pushButton_v->setGeometry(QRect(135, 115, 25, 25));
        pushButton_v->setMaximumSize(QSize(40, 50));
        pushButton_v->setFocusPolicy(Qt::NoFocus);
        pushButton_v->setFlat(false);
        pushButton_en_ch = new QPushButton(centralWidget);
        pushButton_en_ch->setObjectName(QString::fromUtf8("pushButton_en_ch"));
        pushButton_en_ch->setGeometry(QRect(300, 5, 50, 31));
        pushButton_en_ch->setMaximumSize(QSize(16777215, 16777212));
        pushButton_en_ch->setFocusPolicy(Qt::NoFocus);
        pushButton_en_ch->setFlat(false);
        hz_3 = new QPushButton(centralWidget);
        hz_3->setObjectName(QString::fromUtf8("hz_3"));
        hz_3->setGeometry(QRect(85, 40, 25, 25));
        hz_3->setMaximumSize(QSize(40, 60));
        hz_3->setFocusPolicy(Qt::NoFocus);
        hz_3->setFlat(false);
        pushButton_x = new QPushButton(centralWidget);
        pushButton_x->setObjectName(QString::fromUtf8("pushButton_x"));
        pushButton_x->setGeometry(QRect(85, 115, 25, 25));
        pushButton_x->setMaximumSize(QSize(40, 50));
        pushButton_x->setFocusPolicy(Qt::NoFocus);
        pushButton_x->setFlat(false);
        pushButton_y = new QPushButton(centralWidget);
        pushButton_y->setObjectName(QString::fromUtf8("pushButton_y"));
        pushButton_y->setGeometry(QRect(175, 65, 25, 25));
        pushButton_y->setMaximumSize(QSize(40, 50));
        pushButton_y->setFocusPolicy(Qt::NoFocus);
        pushButton_y->setFlat(false);
        pushButton_u = new QPushButton(centralWidget);
        pushButton_u->setObjectName(QString::fromUtf8("pushButton_u"));
        pushButton_u->setGeometry(QRect(200, 65, 25, 25));
        pushButton_u->setMaximumSize(QSize(40, 50));
        pushButton_u->setFocusPolicy(Qt::NoFocus);
        pushButton_u->setFlat(false);
        pushButton_c = new QPushButton(centralWidget);
        pushButton_c->setObjectName(QString::fromUtf8("pushButton_c"));
        pushButton_c->setGeometry(QRect(110, 115, 25, 25));
        pushButton_c->setMaximumSize(QSize(40, 50));
        pushButton_c->setFocusPolicy(Qt::NoFocus);
        pushButton_c->setFlat(false);
        hz_10 = new QPushButton(centralWidget);
        hz_10->setObjectName(QString::fromUtf8("hz_10"));
        hz_10->setGeometry(QRect(260, 40, 25, 25));
        hz_10->setMaximumSize(QSize(40, 60));
        hz_10->setFocusPolicy(Qt::NoFocus);
        hz_10->setFlat(false);
        pushButton_sign_dou = new QPushButton(centralWidget);
        pushButton_sign_dou->setObjectName(QString::fromUtf8("pushButton_sign_dou"));
        pushButton_sign_dou->setGeometry(QRect(235, 115, 25, 25));
        pushButton_sign_dou->setFocusPolicy(Qt::NoFocus);
        pushButton_sign_dou->setFlat(false);
        pushButton_p = new QPushButton(centralWidget);
        pushButton_p->setObjectName(QString::fromUtf8("pushButton_p"));
        pushButton_p->setGeometry(QRect(275, 65, 25, 25));
        pushButton_p->setMaximumSize(QSize(40, 50));
        pushButton_p->setFocusPolicy(Qt::NoFocus);
        pushButton_p->setFlat(false);
        pushButton_d = new QPushButton(centralWidget);
        pushButton_d->setObjectName(QString::fromUtf8("pushButton_d"));
        pushButton_d->setGeometry(QRect(105, 90, 25, 25));
        pushButton_d->setMaximumSize(QSize(40, 50));
        pushButton_d->setFocusPolicy(Qt::NoFocus);
        pushButton_d->setFlat(false);
        pushButton_h = new QPushButton(centralWidget);
        pushButton_h->setObjectName(QString::fromUtf8("pushButton_h"));
        pushButton_h->setGeometry(QRect(180, 90, 25, 25));
        pushButton_h->setMaximumSize(QSize(40, 50));
        pushButton_h->setFocusPolicy(Qt::NoFocus);
        pushButton_h->setFlat(false);
        hz_6 = new QPushButton(centralWidget);
        hz_6->setObjectName(QString::fromUtf8("hz_6"));
        hz_6->setGeometry(QRect(160, 40, 25, 25));
        hz_6->setMaximumSize(QSize(40, 60));
        hz_6->setFocusPolicy(Qt::NoFocus);
        hz_6->setFlat(false);
        pushButton_e = new QPushButton(centralWidget);
        pushButton_e->setObjectName(QString::fromUtf8("pushButton_e"));
        pushButton_e->setGeometry(QRect(100, 65, 25, 25));
        pushButton_e->setMaximumSize(QSize(40, 50));
        pushButton_e->setFocusPolicy(Qt::NoFocus);
        pushButton_e->setFlat(false);
        pushButton_o = new QPushButton(centralWidget);
        pushButton_o->setObjectName(QString::fromUtf8("pushButton_o"));
        pushButton_o->setGeometry(QRect(250, 65, 25, 25));
        pushButton_o->setMaximumSize(QSize(40, 50));
        pushButton_o->setFocusPolicy(Qt::NoFocus);
        pushButton_o->setFlat(false);
        pushButton_a = new QPushButton(centralWidget);
        pushButton_a->setObjectName(QString::fromUtf8("pushButton_a"));
        pushButton_a->setGeometry(QRect(55, 90, 25, 25));
        pushButton_a->setMaximumSize(QSize(40, 50));
        pushButton_a->setFocusPolicy(Qt::NoFocus);
        pushButton_a->setFlat(false);
        hz_9 = new QPushButton(centralWidget);
        hz_9->setObjectName(QString::fromUtf8("hz_9"));
        hz_9->setGeometry(QRect(235, 40, 25, 25));
        hz_9->setMaximumSize(QSize(40, 60));
        hz_9->setFocusPolicy(Qt::NoFocus);
        hz_9->setFlat(false);
        pushButton_s = new QPushButton(centralWidget);
        pushButton_s->setObjectName(QString::fromUtf8("pushButton_s"));
        pushButton_s->setGeometry(QRect(80, 90, 25, 25));
        pushButton_s->setMaximumSize(QSize(40, 50));
        pushButton_s->setFocusPolicy(Qt::NoFocus);
        pushButton_s->setFlat(false);
        pushButton_del = new QPushButton(centralWidget);
        pushButton_del->setObjectName(QString::fromUtf8("pushButton_del"));
        pushButton_del->setGeometry(QRect(310, 40, 40, 25));
        pushButton_del->setBaseSize(QSize(40, 40));
        QPalette palette;
        QBrush brush(QColor(170, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush1(QColor(118, 116, 108, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_del->setPalette(palette);
        QFont font;
        font.setFamily(QString::fromUtf8("\345\256\213\344\275\223"));
        pushButton_del->setFont(font);
        pushButton_del->setFocusPolicy(Qt::NoFocus);
        pushButton_del->setContextMenuPolicy(Qt::NoContextMenu);
        pushButton_del->setFlat(false);
        pushButton_esc = new QPushButton(centralWidget);
        pushButton_esc->setObjectName(QString::fromUtf8("pushButton_esc"));
        pushButton_esc->setGeometry(QRect(10, 65, 40, 25));
        pushButton_esc->setMaximumSize(QSize(100, 50));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        pushButton_esc->setPalette(palette1);
        pushButton_esc->setFocusPolicy(Qt::NoFocus);
        pushButton_esc->setFlat(false);
        pushButton_cap = new QPushButton(centralWidget);
        pushButton_cap->setObjectName(QString::fromUtf8("pushButton_cap"));
        pushButton_cap->setGeometry(QRect(10, 90, 45, 25));
        pushButton_cap->setMaximumSize(QSize(100, 50));
        pushButton_cap->setFocusPolicy(Qt::NoFocus);
        pushButton_cap->setFlat(false);
        pushButton_space = new QPushButton(centralWidget);
        pushButton_space->setObjectName(QString::fromUtf8("pushButton_space"));
        pushButton_space->setGeometry(QRect(280, 115, 71, 25));
        pushButton_space->setFocusPolicy(Qt::NoFocus);
        pushButton_space->setFlat(false);
        pushButton_next = new QPushButton(centralWidget);
        pushButton_next->setObjectName(QString::fromUtf8("pushButton_next"));
        pushButton_next->setGeometry(QRect(285, 40, 25, 25));
        pushButton_next->setMaximumSize(QSize(40, 40));
        pushButton_next->setFocusPolicy(Qt::NoFocus);
        pushButton_next->setFlat(false);
        pushButton_n = new QPushButton(centralWidget);
        pushButton_n->setObjectName(QString::fromUtf8("pushButton_n"));
        pushButton_n->setGeometry(QRect(185, 115, 25, 25));
        pushButton_n->setMaximumSize(QSize(40, 50));
        pushButton_n->setFocusPolicy(Qt::NoFocus);
        pushButton_n->setFlat(false);
        pushButton_sign_fen = new QPushButton(centralWidget);
        pushButton_sign_fen->setObjectName(QString::fromUtf8("pushButton_sign_fen"));
        pushButton_sign_fen->setGeometry(QRect(280, 90, 25, 25));
        pushButton_sign_fen->setMaximumSize(QSize(40, 50));
        pushButton_sign_fen->setFocusPolicy(Qt::NoFocus);
        pushButton_sign_fen->setFlat(false);
        pushButton_w = new QPushButton(centralWidget);
        pushButton_w->setObjectName(QString::fromUtf8("pushButton_w"));
        pushButton_w->setGeometry(QRect(75, 65, 25, 25));
        pushButton_w->setMaximumSize(QSize(40, 50));
        pushButton_w->setFocusPolicy(Qt::NoFocus);
        pushButton_w->setFlat(false);
        pushButton_f = new QPushButton(centralWidget);
        pushButton_f->setObjectName(QString::fromUtf8("pushButton_f"));
        pushButton_f->setGeometry(QRect(130, 90, 25, 25));
        pushButton_f->setMaximumSize(QSize(40, 50));
        pushButton_f->setFocusPolicy(Qt::NoFocus);
        pushButton_f->setFlat(false);
        pushButton_sign_wen = new QPushButton(centralWidget);
        pushButton_sign_wen->setObjectName(QString::fromUtf8("pushButton_sign_wen"));
        pushButton_sign_wen->setGeometry(QRect(35, 115, 25, 25));
        pushButton_sign_wen->setMaximumSize(QSize(40, 50));
        pushButton_sign_wen->setFocusPolicy(Qt::NoFocus);
        pushButton_sign_wen->setFlat(false);
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(140, 5, 111, 30));
        hz_5 = new QPushButton(centralWidget);
        hz_5->setObjectName(QString::fromUtf8("hz_5"));
        hz_5->setGeometry(QRect(135, 40, 25, 25));
        hz_5->setMaximumSize(QSize(40, 60));
        hz_5->setFocusPolicy(Qt::NoFocus);
        hz_5->setFlat(false);
        pushButton_sign_ju = new QPushButton(centralWidget);
        pushButton_sign_ju->setObjectName(QString::fromUtf8("pushButton_sign_ju"));
        pushButton_sign_ju->setGeometry(QRect(260, 115, 25, 25));
        pushButton_sign_ju->setFocusPolicy(Qt::NoFocus);
        pushButton_sign_ju->setFlat(false);
        pinyin = new QPushButton(centralWidget);
        pinyin->setObjectName(QString::fromUtf8("pinyin"));
        pinyin->setGeometry(QRect(14, 5, 71, 31));
        pinyin->setMaximumSize(QSize(80, 40));
        pinyin->setFocusPolicy(Qt::NoFocus);
        pinyin->setContextMenuPolicy(Qt::ActionsContextMenu);
        pinyin->setCheckable(false);
        pinyin->setAutoDefault(false);
        pinyin->setDefault(true);
        pinyin->setFlat(false);
        pushButton_m = new QPushButton(centralWidget);
        pushButton_m->setObjectName(QString::fromUtf8("pushButton_m"));
        pushButton_m->setGeometry(QRect(210, 115, 25, 25));
        pushButton_m->setMaximumSize(QSize(40, 50));
        pushButton_m->setFocusPolicy(Qt::NoFocus);
        pushButton_m->setFlat(false);
        pushButton_b = new QPushButton(centralWidget);
        pushButton_b->setObjectName(QString::fromUtf8("pushButton_b"));
        pushButton_b->setGeometry(QRect(160, 115, 25, 25));
        pushButton_b->setMaximumSize(QSize(40, 50));
        pushButton_b->setFocusPolicy(Qt::NoFocus);
        pushButton_b->setFlat(false);
        pushButton_sign_tan = new QPushButton(centralWidget);
        pushButton_sign_tan->setObjectName(QString::fromUtf8("pushButton_sign_tan"));
        pushButton_sign_tan->setGeometry(QRect(10, 115, 25, 25));
        pushButton_sign_tan->setMaximumSize(QSize(40, 50));
        pushButton_sign_tan->setFocusPolicy(Qt::NoFocus);
        hz_8 = new QPushButton(centralWidget);
        hz_8->setObjectName(QString::fromUtf8("hz_8"));
        hz_8->setGeometry(QRect(210, 40, 25, 25));
        hz_8->setMaximumSize(QSize(40, 60));
        hz_8->setFocusPolicy(Qt::NoFocus);
        hz_8->setFlat(false);
        Keyboard->setCentralWidget(centralWidget);

        retranslateUi(Keyboard);

        QMetaObject::connectSlotsByName(Keyboard);
    } // setupUi

    void retranslateUi(QMainWindow *Keyboard)
    {
        Keyboard->setWindowTitle(QApplication::translate("Keyboard", "Keyboard", 0, QApplication::UnicodeUTF8));
        hz_1->setText(QString());
        pushButton_r->setText(QApplication::translate("Keyboard", "r", 0, QApplication::UnicodeUTF8));
        pushButton_t->setText(QApplication::translate("Keyboard", "t", 0, QApplication::UnicodeUTF8));
        hz_7->setText(QString());
        pushButton_j->setText(QApplication::translate("Keyboard", "j", 0, QApplication::UnicodeUTF8));
        pushButton_l->setText(QApplication::translate("Keyboard", "l", 0, QApplication::UnicodeUTF8));
        pushButton_g->setText(QApplication::translate("Keyboard", "g", 0, QApplication::UnicodeUTF8));
        pushButton_q->setText(QApplication::translate("Keyboard", "q", 0, QApplication::UnicodeUTF8));
        pushButton_pre->setText(QApplication::translate("Keyboard", "<", 0, QApplication::UnicodeUTF8));
        pushButton_z->setText(QApplication::translate("Keyboard", "z", 0, QApplication::UnicodeUTF8));
        pushButton_Enter->setText(QApplication::translate("Keyboard", "\345\233\236\350\275\246", 0, QApplication::UnicodeUTF8));
        pushButton_i->setText(QApplication::translate("Keyboard", "i", 0, QApplication::UnicodeUTF8));
        pushButton_k->setText(QApplication::translate("Keyboard", "k", 0, QApplication::UnicodeUTF8));
        hz_4->setText(QString());
        hz_2->setText(QString());
        pushButton_v->setText(QApplication::translate("Keyboard", "v", 0, QApplication::UnicodeUTF8));
        pushButton_en_ch->setText(QApplication::translate("Keyboard", "\350\213\261\346\226\207", 0, QApplication::UnicodeUTF8));
        hz_3->setText(QString());
        pushButton_x->setText(QApplication::translate("Keyboard", "x", 0, QApplication::UnicodeUTF8));
        pushButton_y->setText(QApplication::translate("Keyboard", "y", 0, QApplication::UnicodeUTF8));
        pushButton_u->setText(QApplication::translate("Keyboard", "u", 0, QApplication::UnicodeUTF8));
        pushButton_c->setText(QApplication::translate("Keyboard", "c", 0, QApplication::UnicodeUTF8));
        hz_10->setText(QString());
        pushButton_sign_dou->setText(QApplication::translate("Keyboard", "\357\274\214", 0, QApplication::UnicodeUTF8));
        pushButton_p->setText(QApplication::translate("Keyboard", "p", 0, QApplication::UnicodeUTF8));
        pushButton_d->setText(QApplication::translate("Keyboard", "d", 0, QApplication::UnicodeUTF8));
        pushButton_h->setText(QApplication::translate("Keyboard", "h", 0, QApplication::UnicodeUTF8));
        hz_6->setText(QString());
        pushButton_e->setText(QApplication::translate("Keyboard", "e", 0, QApplication::UnicodeUTF8));
        pushButton_o->setText(QApplication::translate("Keyboard", "o", 0, QApplication::UnicodeUTF8));
        pushButton_a->setText(QApplication::translate("Keyboard", "a", 0, QApplication::UnicodeUTF8));
        hz_9->setText(QString());
        pushButton_s->setText(QApplication::translate("Keyboard", "s", 0, QApplication::UnicodeUTF8));
        pushButton_del->setText(QApplication::translate("Keyboard", "<-Del", 0, QApplication::UnicodeUTF8));
        pushButton_esc->setText(QApplication::translate("Keyboard", "\345\205\263\351\227\255", 0, QApplication::UnicodeUTF8));
        pushButton_cap->setText(QApplication::translate("Keyboard", "cap", 0, QApplication::UnicodeUTF8));
        pushButton_space->setText(QApplication::translate("Keyboard", "\347\251\272\346\240\274", 0, QApplication::UnicodeUTF8));
        pushButton_next->setText(QApplication::translate("Keyboard", ">", 0, QApplication::UnicodeUTF8));
        pushButton_n->setText(QApplication::translate("Keyboard", "n", 0, QApplication::UnicodeUTF8));
        pushButton_sign_fen->setText(QApplication::translate("Keyboard", "\357\274\233", 0, QApplication::UnicodeUTF8));
        pushButton_w->setText(QApplication::translate("Keyboard", "w", 0, QApplication::UnicodeUTF8));
        pushButton_f->setText(QApplication::translate("Keyboard", "f", 0, QApplication::UnicodeUTF8));
        pushButton_sign_wen->setText(QApplication::translate("Keyboard", "?", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("Keyboard", "<\342\200\224\342\200\224\350\275\257\351\224\256\347\233\230\342\200\224\342\200\224>", 0, QApplication::UnicodeUTF8));
        hz_5->setText(QString());
        pushButton_sign_ju->setText(QApplication::translate("Keyboard", "\343\200\202", 0, QApplication::UnicodeUTF8));
        pinyin->setText(QString());
        pushButton_m->setText(QApplication::translate("Keyboard", "m", 0, QApplication::UnicodeUTF8));
        pushButton_b->setText(QApplication::translate("Keyboard", "b", 0, QApplication::UnicodeUTF8));
        pushButton_sign_tan->setText(QApplication::translate("Keyboard", "!", 0, QApplication::UnicodeUTF8));
        hz_8->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Keyboard: public Ui_Keyboard {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_KEYBOARD_H
